SET TIMEZONE="UTC";

CREATE TABLE IF NOT EXISTS users(
  id serial PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS notes(
  id serial PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content VARCHAR NOT NULL,
  user_id INTEGER NOT NULL,
  attrs JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP NULL,
  CONSTRAINT fk_users
    FOREIGN KEY(user_id)
    REFERENCES users(id)
);
